FROM node:25-alpine AS build
WORKDIR /app
COPY itercraft_front/package.json itercraft_front/package-lock.json ./
RUN npm ci
COPY itercraft_front/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY devsecops/docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
