FROM node:25-alpine AS build
WORKDIR /app
COPY itercraft_front/package.json itercraft_front/package-lock.json ./
RUN npm ci
COPY itercraft_front/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3000
RUN sed -i 's/listen\s*80;/listen 3000;/g' /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
